global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Uno.Extensions.Http.Kiota;
global using Uno.Extensions.Navigation;
global using unoTest.Controls;
global using unoTest.Converters;
global using unoTest.Models;
global using unoTest.Presentation;
global using unoTest.Services;
global using unoTest.Services.Endpoints;
global using unoTest.ViewModels;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
